services:
  db:
    image: postgres:latest
    container_name: bekind_db
    environment:
      POSTGRES_USER: bekind
      POSTGRES_PASSWORD: bekind
      POSTGRES_DB: bekind
    volumes:
      - bekind_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    profiles:
      - prod

  db-dev:
    extends:
      service: db
    ports:
      - "5432:5432"
    profiles:
      - dev

  app:
    environment:
      BEKIND_PORT: 8080
      BEKIND_LOG_LEVEL: info
      BEKIND_LOG_OUTPUT: stdout
      BEKIND_DB_CONN_STRING: "postgresql://peverel:peverel@db/bekind?sslmode=disable"
      BEKIND_MODE: "memory"
    build:
      context: .
      dockerfile: Dockerfile
#      no_cache: true
    container_name: peverel_app
    ports:
      - "8081:8080"
    depends_on:
      - db
    profiles:
      - prod

volumes:
  peverel_data: